import {createSlice} from "@reduxjs/toolkit"

const dataSlice=createSlice({
    name:'data',
    initialState:{
        NH4AverageRates:0,
        PxOyAverageRates:0,
        NO3AverageRates:0,
        NH4DataPerDate:null,
        PxOyDataPerDate:null,
        NO3DataPerDate:null,
        NH4DataPerMonth:[],
        PxOyDataPerMonth:[],
        NO3DataPerMonth:[],
        NH4DataPerYear:[],
        PxOyDataPerYear:[],
        NO3DataPerYear:[],
        recentNH4Year:null,
        recentPxOyYear:null,
        recentNO3Year:null,
        NH4RecentData:[],
        PxOyRecentData:[],
        NO3RecentData:[],
        Arrangements:[]
    },
    reducers:{
        getNH4AverageRates:(state,action)=>{
            state.NH4AverageRates=action.payload;
        },
        getPxOyAverageRates:(state,action)=>{
            state.PxOyAverageRates=action.payload;
        },
        getNO3AverageRates:(state,action)=>{
            state.NO3AverageRates=action.payload;
        },
        getNH4PerDate:(state,action)=>{
            state.NH4DataPerDate=action.payload?.data?.dataRate;
        },
        getPxOyPerDate:(state,action)=>{
            state.PxOyDataPerDate=action.payload?.data?.dataRate;
        },
        getNO3PerDate:(state,action)=>{
            state.NO3DataPerDate=action.payload?.data?.dataRate;
        },
        getNH4PerMonth:(state,action)=>{
            state.NH4DataPerMonth=action.payload;
        },
        getPxOyPerMonth:(state,action)=>{
            state.PxOyDataPerMonth=action.payload;
        },
        getNO3PerMonth:(state,action)=>{
            state.NO3DataPerMonth=action.payload;
        },
        getNH4PerYear:(state,action)=>{
            state.NH4DataPerYear=action.payload;
        },
        getPxOyPerYear:(state,action)=>{
            state.PxOyDataPerYear=action.payload;
        },
        getNO3PerYear:(state,action)=>{
            state.NO3DataPerYear=action.payload;
        },
        setRecentNH4Year:(state,action)=>{
            state.recentNH4Year=action.payload;
        },
        setRecentPxOyYear:(state,action)=>{
            state.recentPxOyYear=action.payload;
        },
        setRecentNO3Year:(state,action)=>{
            state.recentNO3Year=action.payload;
        },
        getNH4RecentData:(state,action)=>{
            state.NH4RecentData=action.payload;
        },
        getPxOyRecentData:(state,action)=>{
            state.PxOyRecentData=action.payload;
        },
        getNO3RecentData:(state,action)=>{
            state.NO3RecentData=action.payload;
        },
        getArrangements:(state,action)=>{
            state.Arrangements=action.payload;
        },
    }
})

const dataActions=dataSlice.actions;

const dataReducers=dataSlice.reducer;
export {dataActions,dataReducers}